apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls-ga
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
  - secretName: ingress-tls-csi-ga
    type: kubernetes.io/tls
    data: 
    - objectName: aks-ingress-cert-tls
      key: tls.key
    - objectName: aks-ingress-cert-tls
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: <client id>
    keyvaultName: ingresskey                 # the name of the AKV instance
    objects: |
      array:
        - |
          objectName: aks-ingress-cert-tls
          objectType: secret
    tenantId:  72f988bf-86f1-41af-91ab-2d7cd011db47                    # the tenant ID of the AKV instance