---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mise-appsettings
  namespace: ingress-basic
data:
  # TODO: figure out out settings https://identitydivision.visualstudio.com/DevEx/_git/MISE?path=%2Fdocs%2Fcontainer%2FConfiguration.md&version=GBmaster&_a=preview
  appsettings.json: |
    {
      "AzureAd": {
          "Instance": "https://login.microsoftonline.com/",
          "ClientId": "a4c2469b-cf84-4145-8f5f-cb7bacf814bc",
          "TenantId": "7f58f645-c190-4ce5-9de4-e2b7acd2a6ab",
          "ShowPII": false,
          "MinimumDataClassificationCategory": "SystemMetadata",
          "Logging": {
              "LogLevel": "Warning"
          },
          "Modules": {
              "TrV2": {
                  "ModuleType": "TrV2Module",
                  "Enabled": true
              }
          },
          "InboundPolicies": [
              {
                  "Label": "aksrp-arm-inbound-policy",
                  "Authority": "https://sts.windows.net/33e01921-4d64-4f8c-a055-5bdaffd5e33d/v2.0", // TODO
                  "ClientId": "https://management.azure.com", // TODO
                  "AuthenticationSchemes": [
                      "PoP"
                  ],
                  "TokenTypes": [
                      "AppToken"
                  ]
                  // TODO
                  // "ServerNoncePolicy": {
                  //     "ServerNonceSigningCredentials": {
                  //         "Algorithm": "HS256",
                  //         "SymmetricKeyDescription": {
                  //             "Base64EncodedValue": "base64",
                  //             "SourceType": "Base64Encoded"
                  //         }
                  //     }
                  // }
              }
          ]
      },
      "AllowedHosts": "*",
      "Kestrel": {
          "Endpoints": {
              "Http": {
                  "Url": "http://0.0.0.0:5000"
              }
          }
      },
      "Logging": {
            "Console": {
                "LogLevel": {
                    "Default": "Warning",
                    "Microsoft": "Error",
                    "Microsoft.Hosting.Lifetime": "Information"
                }
            }
        }
    }
