apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl-meshtls-test
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: curl-meshtls-test
spec:
  identityRefs:
    - kind: ServiceAccount
      name: curl-meshtls-test